# Generated by Django 4.2.23 on 2025-06-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='plandevice',
            unique_together={('plan', 'name')},
        ),
    ]
