# Generated by Django 4.2.23 on 2025-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_populate_device_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandevice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]